### ISSUE TITLE
Fail to create ETS knxprod file per the guidance in README.md

### ISSUE THREAD

**Issue by betamoojw** [OpenKNX/OAM-SmartHomeBridge#5]
It will fail to create ETS knxprod file as below.
![image](https://github.com/OpenKNX/OAM-SmartHomeBridge/assets/40590760/87b3f5bb-30f7-4765-ad4f-2bcb5787ef52)

With further investigation, it will fix this issue as below and now successfully create SmartHomeBridge.knxprod.
![image](https://github.com/OpenKNX/OAM-SmartHomeBridge/assets/40590760/8570aca5-9dd2-48de-9dc3-da90dfc6e4b1)

Additionally, we should update the README.md as below for consistency.
![image](https://github.com/OpenKNX/OAM-SmartHomeBridge/assets/40590760/e8748196-267a-4fa1-aae5-8b3c0a11f1a4)

**Comment by mgeramb** [comment]
Thank you, for your comments, sorry, I have not seen it early. Currently there is a complete reworked version in the repo. The build should work with the platformio tool. I'am currently planning to make a first release with a prebuild firmware by the end of January.
